### ISSUE TITLE
How can I add tags to increment counter?

### ISSUE THREAD

**Issue by Avik1993** [gphat/censorinus#31]
I would like to add tags to my counters when sending data to telegraf.
Similar to this:

```

> time                code host     message metric_type value
> ----                ---- ----     ------- ----------- -----
> 1556787040000000000 200  server-3 success counter     1
> 1556787120000000000 200  server-3 success counter     5
> 

```

Here, code and message being the custom tag, I did through python client.
Same can be done using this library?

**Comment by gphat** [comment]
Tags can be added at the time the increment/gauge/timer is recorded, as show [in these examples](https://github.com/gphat/censorinus#dogstatsd), specifically with the `tags` parameter.

Closing this, as it's a question and not an issue. Thanks!
