### ISSUE TITLE
Publish 2.13 build

### ISSUE THREAD

**Issue by mathieuancelinserli** [gphat/censorinus#34]
Hey @gphat, i've seen that scala 2.13 support is merged in the master branch. Is it possible to publish it ?

**Comment by juanfi** [comment]
Hi @gphat, I'm interested too, do you have any idea when this would be published?

**Comment by gphat** [comment]
Sure thing folks, lemme dig up the instructions I haven't done this in a minute. :)

**Comment by gphat** [comment]
Done! I see that 2.13 went up to Sonatype. Please let me know if you run into any problems.
