### ISSUE TITLE
Make client a parameter to `DogStatsDClient`

### ISSUE THREAD

**Issue by tixxit** [gphat/censorinus#7]
This will make it easier to pass in fake/mock clients and test dogstatsdclient. Specifically, I'm currently having problems hitting socket limits since I can't stop my mocked `DogStatsDClient` from creating a UDPSender in another class that uses `DogStatsDClient` (using ScalaMock).

**Comment by gphat** [comment]
Fixed!

**Comment by gphat** [comment]
Released as v2.0.2.
